"""Geometry and animation regression tests without touching a real strip."""
# AI: below section was generated by an AI
from copy import deepcopy
import importlib
import unittest

from test_segments import model, segment

effects = importlib.import_module("segment_unit.effects")
layout = importlib.import_module("segment_unit.layout")


class LayoutTests(unittest.TestCase):
    def test_distribution_preserves_ids_and_covers_cut_strip(self):
        original = [segment("a", 1, 9), segment("b", 10, 18)]
        updated = layout.distribute_segments(original, 5, 18)
        self.assertEqual([s["id"] for s in updated[:2]], ["a", "b"])
        self.assertEqual(sum(s["end"] - s["start"] + 1 for s in updated), 18)
        self.assertEqual(updated[-1]["end"], 18)
        self.assertEqual(len({s["id"] for s in updated}), 5)
        self.assertEqual(layout.distribute_segments(updated, 1, 18)[0]["id"], "a")

    def test_resize_reflows_following_segments_without_mutating(self):
        original = [segment("a", 1, 6), segment("b", 7, 12)]
        snapshot = deepcopy(original)
        updated = layout.resize_segment(original, "a", "First", 1, 3, 18, True)
        self.assertEqual([(s["start"], s["end"]) for s in updated], [(1, 3), (4, 9)])
        self.assertEqual(original, snapshot)
        self.assertEqual(updated[0]["id"], "a")

    def test_append_and_overflow(self):
        original = [segment("a", 1, 6)]
        updated = layout.resize_segment(original, "b", "B", 1, 12, 18, True)
        self.assertEqual((updated[1]["start"], updated[1]["end"]), (7, 18))
        with self.assertRaises(ValueError):
            layout.resize_segment(original, "b", "B", 1, 13, 18, True)
        with self.assertRaises(ValueError):
            layout.resize_segment(original, "b", "B", 1, 3, 18, False)
        with self.assertRaises(ValueError):
            layout.distribute_segments([], 13, 18)


class EffectTests(unittest.TestCase):
    def render(self, regions, states, names, t, total=18):
        return effects.render_frame(regions, states, total, 258, "test", names, t)

    def test_rainbow_moves_and_never_exceeds_budget(self):
        regions = [segment("a", 1, 9), segment("b", 10, 18)]
        states = model.restore_states(regions, {})
        for key in states:
            states = model.changed_states(states, key, True)
        before = deepcopy(states)
        first = self.render(regions, states, {"a": "Rainbow", "b": "Rainbow"}, 0)
        second = self.render(regions, states, {"a": "Rainbow", "b": "Rainbow"}, 1)
        self.assertNotEqual(first, second)
        self.assertEqual(len(first["elm"]["steps"]), 12)
        self.assertEqual(sum(s[-1] for s in first["elm"]["steps"]), 18)
        self.assertEqual(states, before)

    def test_static_whites_gaps_and_tail_are_preserved(self):
        regions = [segment("a", 2, 9), segment("b", 11, 15)]
        states = model.restore_states(regions, {})
        states = model.changed_states(states, "a", True)
        states = model.changed_states(states, "b", True, rgbww=(0, 0, 0, 20, 200), brightness=128)
        steps = self.render(regions, states, {"a": "Rainbow"}, 1)["elm"]["steps"]
        self.assertEqual(len(steps), 12)
        self.assertEqual(sum(s[-1] for s in steps), 18)
        self.assertEqual(steps[-2][1:6], [0, 0, 0, 200, 20])
        self.assertEqual(steps[-2][7], 50)
        self.assertEqual(steps[-1][-1], 3)
        self.assertEqual(steps[-1][7], 0)

    def test_breathe_preserves_white_channels_and_chase_moves(self):
        regions = [segment("a", 1, 18)]
        states = model.changed_states(model.restore_states(regions, {}), "a", True, rgbww=(0, 0, 0, 0, 255), brightness=200)
        low = self.render(regions, states, {"a": "Breathe"}, 0)["elm"]["steps"][0]
        high = self.render(regions, states, {"a": "Breathe"}, 3)["elm"]["steps"][0]
        self.assertEqual(low[4], 255)
        self.assertGreater(high[7], low[7])
        a = self.render(regions, states, {"a": "Chase"}, 0)
        b = self.render(regions, states, {"a": "Chase"}, 2)
        self.assertNotEqual(a, b)

    def test_twelve_segments_degrade_without_overflow(self):
        regions = layout.distribute_segments([], 12, 18)
        states = model.restore_states(regions, {})
        for key in states:
            states[key]["on"] = True
        steps = self.render(regions, states, dict.fromkeys(states, "Rainbow"), 1)["elm"]["steps"]
        self.assertEqual(len(steps), 12)
        self.assertTrue(all(s[-1] >= 1 for s in steps))

    def test_effect_off_is_identical_to_static_encoder(self):
        regions = [segment("a", 1, 18)]
        states = model.restore_states(regions, {})
        self.assertEqual(self.render(regions, states, {"a": "Rainbow"}, 0), {"state": False})
        states["a"]["on"] = True
        self.assertEqual(self.render(regions, states, {"a": "off"}, 0),
                         model.compose_frame(regions, states, 18, 258, "test"))


if __name__ == "__main__":
    unittest.main()
# AI: end
