"""Isolated adapter tests; HA lifecycle is not emulated or claimed as tested."""
# AI: below section was generated by an AI
import asyncio
from copy import deepcopy
import importlib
from pathlib import Path
import sys
import types
import unittest
from unittest.mock import patch


class HAError(Exception):
    pass


class BaseCoordinator:
    def __init__(self, *args, **kwargs):
        self.data = None

    def async_set_updated_data(self, data):
        self.data = data

    def async_set_update_error(self, error):
        self.error = error


class MemoryStore:
    def __init__(self, *args):
        self.saved = None

    async def async_load(self):
        return self.saved

    def async_delay_save(self, callback, delay):
        self.saved = deepcopy(callback())


def load_adapter():
    """Substitute only HA infrastructure to test our write transaction logic."""
    replacements = {}
    for name in ("homeassistant", "homeassistant.exceptions", "homeassistant.helpers",
                 "homeassistant.helpers.storage", "homeassistant.helpers.update_coordinator"):
        replacements[name] = types.ModuleType(name)
    replacements["homeassistant.exceptions"].HomeAssistantError = HAError
    replacements["homeassistant.helpers.storage"].Store = MemoryStore
    update = replacements["homeassistant.helpers.update_coordinator"]
    update.DataUpdateCoordinator = BaseCoordinator
    update.UpdateFailed = HAError
    pkg = types.ModuleType("adapter_unit")
    pkg.__path__ = [str(Path(__file__).resolve().parents[1] / "custom_components/wiz_segments")]
    sys.modules["adapter_unit"] = pkg
    with patch.dict(sys.modules, replacements):
        return importlib.import_module("adapter_unit.coordinator")


adapter = load_adapter()


class FakeStrip:
    def __init__(self):
        self.pilot = {"state": False, "sceneId": 258}
        self.frames = []
        self.reject = False

    async def request(self, method, params=None):
        await asyncio.sleep(0)
        if method == "getPilot":
            return dict(self.pilot)
        if self.reject:
            raise adapter.WizError("simulated failure")
        self.frames.append(deepcopy(params))
        self.pilot = {"state": params["state"], "sceneId": 258}
        return {"success": True}


class CoordinatorTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        entry = types.SimpleNamespace(entry_id="test", options={}, data={
            "total_blocks": 18, "slot": 258, "segments": [
                {"id": "a", "name": "A", "start": 1, "end": 9},
                {"id": "b", "name": "B", "start": 10, "end": 18}]})
        self.strip = FakeStrip()
        self.coordinator = adapter.SegmentCoordinator(None, entry, self.strip, {"mac": "test"})

    async def test_simultaneous_commands_preserve_both_regions(self):
        await asyncio.gather(self.coordinator.async_set_segment("a", True, (255, 0, 0), 128),
                             self.coordinator.async_set_segment("b", True, (0, 255, 0), 64))
        self.assertEqual(len(self.strip.frames), 2)
        steps = self.strip.frames[-1]["elm"]["steps"]
        self.assertEqual([s[1:4] for s in steps], [[255, 0, 0], [0, 255, 0]])
        self.assertEqual([s[7] for s in steps], [50, 25])

    async def test_rejected_write_does_not_commit_candidate(self):
        await self.coordinator.async_set_segment("a", True, (255, 0, 0))
        before = deepcopy(self.coordinator.states)
        self.strip.reject = True
        with self.assertRaises(HAError):
            await self.coordinator.async_set_segment("b", True)
        self.assertEqual(self.coordinator.states, before)
        self.assertFalse(self.coordinator.frame_known)

    async def test_startup_never_replays_saved_on_states(self):
        self.coordinator.store.saved = {"a": {"on": True, "rgb": [255, 0, 0], "brightness": 50}}
        await self.coordinator.async_load()
        self.assertTrue(self.coordinator.states["a"]["on"])
        self.assertEqual(self.strip.frames, [])
        self.assertFalse(self.coordinator.frame_known)

    async def test_off_does_not_black_out_external_scene(self):
        self.strip.pilot = {"state": True, "sceneId": 11}
        with self.assertRaises(HAError):
            await self.coordinator.async_set_segment("a", False)
        self.assertEqual(self.strip.frames, [])

    async def test_switching_one_region_off_preserves_the_other(self):
        await self.coordinator.async_set_segment("a", True, (255, 0, 0))
        await self.coordinator.async_set_segment("b", True, (0, 0, 255))
        await self.coordinator.async_set_segment("a", False)
        steps = self.strip.frames[-1]["elm"]["steps"]
        self.assertEqual([s[1:4] for s in steps], [[0, 0, 0], [0, 0, 255]])

    async def test_warm_and_cold_regions_remain_independent(self):
        await self.coordinator.async_set_segment("a", True, rgbww=(0, 0, 0, 0, 255))
        await self.coordinator.async_set_segment("b", True, rgbww=(0, 0, 0, 255, 0))
        await self.coordinator.async_set_segment("a", True, brightness=128)
        steps = self.strip.frames[-1]["elm"]["steps"]
        self.assertEqual([s[1:6] for s in steps], [[0, 0, 0, 255, 0], [0, 0, 0, 0, 255]])
        self.assertEqual([s[7] for s in steps], [50, 25])
        self.assertEqual(self.coordinator.store.saved["b"]["cold_white"], 255)


if __name__ == "__main__":
    unittest.main()
# AI: end
