"""Isolated adapter tests; HA lifecycle is not emulated or claimed as tested."""
# AI: below section was generated by an AI
import asyncio
from copy import deepcopy
import importlib
from pathlib import Path
import sys
import types
import unittest
from unittest.mock import patch


class HAError(Exception):
    pass


class BaseCoordinator:
    def __init__(self, *args, **kwargs):
        self.data = None
        self.hass = types.SimpleNamespace(async_create_background_task=lambda coro, name: asyncio.create_task(coro))

    def async_set_updated_data(self, data):
        self.data = data

    def async_set_update_error(self, error):
        self.error = error


class MemoryStore:
    def __init__(self, *args):
        self.saved = None

    async def async_load(self):
        return self.saved

    def async_delay_save(self, callback, delay):
        self.saved = deepcopy(callback())


def load_adapter():
    """Substitute only HA infrastructure to test our write transaction logic."""
    replacements = {}
    for name in ("homeassistant", "homeassistant.exceptions", "homeassistant.helpers",
                 "homeassistant.helpers.storage", "homeassistant.helpers.update_coordinator"):
        replacements[name] = types.ModuleType(name)
    replacements["homeassistant.exceptions"].HomeAssistantError = HAError
    replacements["homeassistant.helpers.storage"].Store = MemoryStore
    update = replacements["homeassistant.helpers.update_coordinator"]
    update.DataUpdateCoordinator = BaseCoordinator
    update.UpdateFailed = HAError
    pkg = types.ModuleType("adapter_unit")
    pkg.__path__ = [str(Path(__file__).resolve().parents[1] / "custom_components/wiz_segments")]
    sys.modules["adapter_unit"] = pkg
    with patch.dict(sys.modules, replacements):
        return importlib.import_module("adapter_unit.coordinator")


adapter = load_adapter()


class FakeStrip:
    def __init__(self):
        self.pilot = {"state": False, "sceneId": 258}
        self.frames = []
        self.reject = False

    async def request(self, method, params=None):
        await asyncio.sleep(0)
        if method == "getPilot":
            return dict(self.pilot)
        if self.reject:
            raise adapter.WizError("simulated failure")
        self.frames.append(deepcopy(params))
        self.pilot = {"state": params["state"], "sceneId": 258}
        return {"success": True}


class CoordinatorTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        entry = types.SimpleNamespace(entry_id="test", options={}, data={
            "total_blocks": 18, "slot": 258, "segments": [
                {"id": "a", "name": "A", "start": 1, "end": 9},
                {"id": "b", "name": "B", "start": 10, "end": 18}]})
        self.strip = FakeStrip()
        entry.async_create_background_task = lambda hass, coro, name, eager_start=False: asyncio.create_task(coro)
        self.coordinator = adapter.SegmentCoordinator(None, entry, self.strip, {"mac": "test"})

    async def asyncTearDown(self):
        await self.coordinator.async_stop_effects()

    async def test_animation_preserves_other_segment_and_stops_for_external_scene(self):
        await self.coordinator.async_set_segment("b", True, rgbww=(0, 0, 0, 0, 255))
        await self.coordinator.async_set_segment("a", True, effect="Rainbow")
        saved = deepcopy(self.coordinator.store.saved)
        await self.coordinator._async_effect_tick()
        self.assertEqual(self.strip.frames[-1]["elm"]["steps"][-1][4], 255)
        self.assertEqual(self.coordinator.store.saved, saved)
        count = len(self.strip.frames)
        self.strip.pilot = {"state": True, "sceneId": 11}
        await self.coordinator._async_effect_tick()
        self.assertEqual(len(self.strip.frames), count)
        self.assertFalse(self.coordinator.frame_known)
        self.assertEqual(self.coordinator.effects["a"], "off")
        self.assertIsNone(self.coordinator._effect_timer)

    async def test_effect_failure_stops_without_committing_preferences(self):
        await self.coordinator.async_set_segment("a", True, effect="Breathe")
        saved = deepcopy(self.coordinator.states)
        self.strip.reject = True
        await self.coordinator._async_effect_tick()
        self.assertEqual(self.coordinator.states, saved)
        self.assertEqual(self.coordinator.effects["a"], "off")
        self.assertIsNone(self.coordinator._effect_timer)

    async def test_manual_color_cancels_effect_brightness_preserves_it(self):
        await self.coordinator.async_set_segment("a", True, effect="Rainbow")
        await self.coordinator.async_set_segment("a", True, brightness=80)
        self.assertEqual(self.coordinator.effects["a"], "Rainbow")
        await self.coordinator.async_set_segment("a", True, rgbww=(255, 0, 0, 0, 0))
        self.assertEqual(self.coordinator.effects["a"], "off")
        self.assertEqual(self.strip.frames[-1]["elm"]["steps"][0][1:4], [255, 0, 0])

    async def test_shutdown_prevents_further_frames(self):
        await self.coordinator.async_set_segment("a", True, effect="Chase")
        await self.coordinator.async_stop_effects()
        count = len(self.strip.frames)
        await self.coordinator._async_effect_tick()
        self.assertEqual(len(self.strip.frames), count)
        self.assertIsNone(self.coordinator._effect_timer)
        with self.assertRaises(HAError):
            await self.coordinator.async_set_segment("a", True)

    async def test_real_timer_drives_frames_and_shutdown_cancels_it(self):
        self.coordinator.settings["effect_fps"] = 5
        await self.coordinator.async_set_segment("a", True, effect="Rainbow")
        await asyncio.sleep(0.25)
        self.assertGreaterEqual(len(self.strip.frames), 2)
        await self.coordinator.async_stop_effects()
        count = len(self.strip.frames)
        await asyncio.sleep(0.25)
        self.assertEqual(len(self.strip.frames), count)

    async def test_unload_cancels_in_flight_animation(self):
        await self.coordinator.async_set_segment("a", True, effect="Rainbow")
        entered = asyncio.Event()
        original = self.strip.request

        async def slow_request(method, params=None):
            if method == "setPilot":
                entered.set()
                await asyncio.Event().wait()
            return await original(method, params)

        self.strip.request = slow_request
        self.coordinator._effect_timer.cancel()
        self.coordinator._start_effect_tick()
        await asyncio.wait_for(entered.wait(), 1)
        await asyncio.wait_for(self.coordinator.async_stop_effects(), 1)
        self.assertIsNone(self.coordinator._effect_task)
        self.assertIsNone(self.coordinator._effect_timer)

    async def test_simultaneous_commands_preserve_both_regions(self):
        await asyncio.gather(self.coordinator.async_set_segment("a", True, (255, 0, 0), 128),
                             self.coordinator.async_set_segment("b", True, (0, 255, 0), 64))
        self.assertEqual(len(self.strip.frames), 2)
        steps = self.strip.frames[-1]["elm"]["steps"]
        self.assertEqual([s[1:4] for s in steps], [[255, 0, 0], [0, 255, 0]])
        self.assertEqual([s[7] for s in steps], [50, 25])

    async def test_rejected_write_does_not_commit_candidate(self):
        await self.coordinator.async_set_segment("a", True, (255, 0, 0))
        before = deepcopy(self.coordinator.states)
        self.strip.reject = True
        with self.assertRaises(HAError):
            await self.coordinator.async_set_segment("b", True)
        self.assertEqual(self.coordinator.states, before)
        self.assertFalse(self.coordinator.frame_known)

    async def test_startup_never_replays_saved_on_states(self):
        self.coordinator.store.saved = {"a": {"on": True, "rgb": [255, 0, 0], "brightness": 50}}
        await self.coordinator.async_load()
        self.assertTrue(self.coordinator.states["a"]["on"])
        self.assertEqual(self.strip.frames, [])
        self.assertFalse(self.coordinator.frame_known)

    async def test_off_does_not_black_out_external_scene(self):
        self.strip.pilot = {"state": True, "sceneId": 11}
        with self.assertRaises(HAError):
            await self.coordinator.async_set_segment("a", False)
        self.assertEqual(self.strip.frames, [])

    async def test_switching_one_region_off_preserves_the_other(self):
        await self.coordinator.async_set_segment("a", True, (255, 0, 0))
        await self.coordinator.async_set_segment("b", True, (0, 0, 255))
        await self.coordinator.async_set_segment("a", False)
        steps = self.strip.frames[-1]["elm"]["steps"]
        self.assertEqual([s[1:4] for s in steps], [[0, 0, 0], [0, 0, 255]])

    async def test_warm_and_cold_regions_remain_independent(self):
        await self.coordinator.async_set_segment("a", True, rgbww=(0, 0, 0, 0, 255))
        await self.coordinator.async_set_segment("b", True, rgbww=(0, 0, 0, 255, 0))
        await self.coordinator.async_set_segment("a", True, brightness=128)
        steps = self.strip.frames[-1]["elm"]["steps"]
        self.assertEqual([s[1:6] for s in steps], [[0, 0, 0, 255, 0], [0, 0, 0, 0, 255]])
        self.assertEqual([s[7] for s in steps], [50, 25])
        self.assertEqual(self.coordinator.store.saved["b"]["cold_white"], 255)


if __name__ == "__main__":
    unittest.main()
# AI: end
