"""Offline tests for real frame composition and UDP transport, without HA."""
# AI: below section was generated by an AI
import asyncio
import importlib
import json
from pathlib import Path
import sys
import types
import unittest

# Load the pure modules without importing the HA integration entry point.
ROOT = Path(__file__).resolve().parents[1] / "custom_components" / "wiz_segments"
package = types.ModuleType("segment_unit")
package.__path__ = [str(ROOT)]
sys.modules["segment_unit"] = package
model = importlib.import_module("segment_unit.model")
protocol = importlib.import_module("segment_unit.protocol")


def segment(key, start, end):
    return {"id": key, "name": key, "start": start, "end": end}


class FrameTests(unittest.TestCase):
    def setUp(self):
        self.layout = [segment("a", 1, 3), segment("b", 4, 6), segment("c", 7, 9)]
        self.states = model.restore_states(self.layout, {})

    def test_calibrated_pattern_and_explicit_dark_tail(self):
        states = self.states
        for key, rgb in zip("abc", ((255, 0, 0), (0, 255, 0), (0, 0, 255))):
            states = model.changed_states(states, key, True, rgb, 26)
        frame = model.compose_frame(self.layout, states, 18, 258, "test")
        steps = frame["elm"]["steps"]
        self.assertEqual([s[-1] for s in steps], [3, 3, 3, 9])
        self.assertEqual([s[1:4] for s in steps], [[255, 0, 0], [0, 255, 0], [0, 0, 255], [0, 0, 0]])
        self.assertEqual([s[7] for s in steps], [10, 10, 10, 0])
        self.assertTrue(all(len(s) == 13 for s in steps))

    def test_one_change_preserves_others_and_does_not_mutate_old_frame(self):
        first = model.changed_states(self.states, "a", True, (255, 0, 0), 25)
        second = model.changed_states(first, "b", True, (0, 255, 0), 128)
        third = model.changed_states(second, "a", False)
        self.assertTrue(first["a"]["on"])
        self.assertFalse(first["b"]["on"])
        self.assertEqual(second["b"], third["b"])
        self.assertFalse(third["a"]["on"])

    def test_all_off_sends_only_power_command(self):
        self.assertEqual(model.compose_frame(self.layout, self.states, 18, 258, "x"), {"state": False})

    def test_zero_brightness_switches_off_and_retains_preference(self):
        states = model.changed_states(self.states, "a", True, brightness=0)
        self.assertFalse(states["a"]["on"])
        self.assertEqual(states["a"]["brightness"], 64)

    def test_unknown_external_state_resets_other_segments(self):
        first = model.changed_states(self.states, "a", True)
        second = model.changed_states(first, "b", True, reset_others=True)
        self.assertFalse(second["a"]["on"])
        self.assertTrue(second["b"]["on"])

    def test_gaps_and_tail_are_dark(self):
        layout = [segment("a", 3, 4), segment("b", 8, 9)]
        states = model.changed_states(model.restore_states(layout, {}), "a", True)
        steps = model.compose_frame(layout, states, 18, 258, "x")["elm"]["steps"]
        self.assertEqual([s[-1] for s in steps], [2, 2, 3, 2, 9])
        self.assertEqual(sum(s[-1] for s in steps), 18)

    def test_invalid_layouts(self):
        for layout in ([], [segment("a", 0, 2)], [segment("a", 3, 2)],
                       [segment("a", 1, 5), segment("b", 5, 8)],
                       [segment("a", 1, 2), segment("a", 4, 5)], [segment("a", 1, 19)]):
            with self.subTest(layout=layout), self.assertRaises(ValueError):
                model.validate_layout(layout, 18)

    def test_gaps_count_towards_firmware_limit(self):
        layout = [segment(str(i), 2*i+1, 2*i+1) for i in range(7)]
        with self.assertRaisesRegex(ValueError, "too_many_steps"):
            model.validate_layout(layout, 18)
        model.validate_layout([segment(str(i), i+1, i+1) for i in range(12)], 12)

    def test_corrupt_preferences_use_defaults(self):
        result = model.restore_states(self.layout, {"a": {"rgb": [999, 0, 0], "brightness": -1}, "b": None})
        self.assertEqual(result, self.states)

    def test_bounds_and_black(self):
        for value in (-1, 256, True):
            with self.assertRaises(ValueError):
                model.changed_states(self.states, "a", True, brightness=value)
        black = model.changed_states(self.states, "a", True, (0, 0, 0))
        self.assertEqual(model.compose_frame(self.layout, black, 18, 258, "x"), {"state": False})

    def test_white_channel_order_matches_visual_test(self):
        for ha_color, wire_color in [((0, 0, 0, 0, 255), [0, 0, 0, 255, 0]),
                                     ((0, 0, 0, 255, 0), [0, 0, 0, 0, 255]),
                                     ((1, 2, 3, 40, 50), [1, 2, 3, 50, 40])]:
            with self.subTest(ha_color=ha_color):
                state = model.changed_states(self.states, "a", True, rgbww=ha_color, brightness=128)
                frame = model.compose_frame(self.layout, state, 18, 258, "x")
                self.assertTrue(frame["state"])
                self.assertEqual(frame["elm"]["steps"][0][1:6], wire_color)
                self.assertEqual(frame["elm"]["steps"][0][7], 50)

    def test_white_only_turn_off_and_brightness_preserve_color(self):
        state = model.changed_states(self.states, "a", True, rgbww=(0, 0, 0, 0, 255))
        dimmed = model.changed_states(state, "a", True, brightness=128)
        self.assertEqual(dimmed["a"]["warm_white"], 255)
        self.assertTrue(model.has_output(dimmed["a"]))
        off = model.changed_states(dimmed, "a", False)
        self.assertEqual(model.compose_frame(self.layout, off, 18, 258, "x"), {"state": False})
        self.assertEqual(off["a"]["warm_white"], 255)

    def test_rgb_command_clears_previous_whites(self):
        state = model.changed_states(self.states, "a", True, rgbww=(0, 0, 0, 40, 80))
        state = model.changed_states(state, "a", True, rgb=(255, 0, 0))
        self.assertEqual((state["a"]["cold_white"], state["a"]["warm_white"]), (0, 0))

    def test_rgbww_persistence_and_legacy_migration(self):
        legacy = model.restore_states(self.layout, {"a": {"rgb": [1, 2, 3], "on": True}})
        self.assertEqual((legacy["a"]["cold_white"], legacy["a"]["warm_white"]), (0, 0))
        state = model.changed_states(legacy, "a", True, rgbww=(1, 2, 3, 40, 80))
        self.assertEqual(model.restore_states(self.layout, state), state)

    def test_rejects_invalid_rgbww_without_mutation(self):
        for value in [(0, 0, 0), (0, 0, 0, -1, 255), (0, 0, 0, 255, 256), (0, 0, 0, True, 0)]:
            with self.subTest(value=value), self.assertRaises(ValueError):
                model.changed_states(self.states, "a", True, rgbww=value)
        self.assertEqual(self.states, model.restore_states(self.layout, {}))


class Device(asyncio.DatagramProtocol):
    def __init__(self, handler):
        self.handler = handler

    def connection_made(self, transport):
        self.transport = transport

    def datagram_received(self, data, address):
        self.handler(self.transport, address, json.loads(data))


class TransportTests(unittest.IsolatedAsyncioTestCase):
    async def setup_peer(self, handler):
        transport, _ = await asyncio.get_running_loop().create_datagram_endpoint(
            lambda: Device(handler), local_addr=("127.0.0.1", 0))
        self.addCleanup(transport.close)
        return protocol.WizClient("127.0.0.1", transport.get_extra_info("sockname")[1], timeout=0.05)

    async def test_ignores_malformed_and_other_methods(self):
        def handler(transport, addr, packet):
            for raw in (b"broken", b"[]", b'{"method":"syncPilot"}',
                        json.dumps({"method": packet["method"], "result": {"state": False}}).encode()):
                transport.sendto(raw, addr)
        client = await self.setup_peer(handler)
        self.assertEqual(await client.request("getPilot"), {"state": False})

    async def test_rejection_propagates(self):
        def handler(transport, addr, packet):
            transport.sendto(json.dumps({"method": packet["method"], "error": {"code": -32602}}).encode(), addr)
        client = await self.setup_peer(handler)
        with self.assertRaises(protocol.WizError):
            await client.request("setPilot", {"state": True})

    async def test_requires_positive_ack(self):
        def handler(transport, addr, packet):
            transport.sendto(json.dumps({"method": packet["method"], "result": {"success": False}}).encode(), addr)
        client = await self.setup_peer(handler)
        with self.assertRaises(protocol.WizError):
            await client.request("setPilot", {"state": True})

    async def test_retry_after_lost_packet(self):
        calls = []
        def handler(transport, addr, packet):
            calls.append(packet)
            if len(calls) == 2:
                transport.sendto(json.dumps({"method": packet["method"], "result": {"success": True}}).encode(), addr)
        client = await self.setup_peer(handler)
        self.assertTrue((await client.request("setPilot", {"state": False}))["success"])
        self.assertEqual(len(calls), 2)

    async def test_timeout_is_bounded(self):
        client = await self.setup_peer(lambda *_: None)
        with self.assertRaises(protocol.WizError):
            await client.request("getPilot")


if __name__ == "__main__":
    unittest.main()
# AI: end
