"""WiZ RGBIC segment lights, controlled directly over the local network."""
# AI: below section was generated by an AI
from homeassistant.const import Platform, EVENT_HOMEASSISTANT_STOP
from homeassistant.exceptions import ConfigEntryNotReady
from homeassistant.helpers import entity_registry as er

from .const import DOMAIN, MODULE
from .coordinator import SegmentCoordinator
from .model import validate_layout
from .protocol import WizClient, WizError

PLATFORMS = [Platform.LIGHT]


async def async_setup_entry(hass, entry):
    """Verify the physical device before exposing its configured regions."""
    settings = {**entry.data, **entry.options}
    validate_layout(settings["segments"], settings["total_blocks"])
    client = WizClient(settings["host"])
    try:
        system = await client.request("getSystemConfig")
    except WizError as err:
        raise ConfigEntryNotReady(str(err)) from err
    if system.get("moduleName") != MODULE or system.get("mac", "").lower() != entry.unique_id:
        raise ConfigEntryNotReady("The IP belongs to a different or unsupported device")
    coordinator = SegmentCoordinator(hass, entry, client, system)
    await coordinator.async_load()
    await coordinator.async_config_entry_first_refresh()
    registry = er.async_get(hass)
    expected = {f"{entry.unique_id}_{segment['id']}" for segment in coordinator.segments}
    for entity in er.async_entries_for_config_entry(registry, entry.entry_id):
        if entity.platform == DOMAIN and entity.unique_id not in expected:
            registry.async_remove(entity.entity_id)
    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = coordinator
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(async_reload_entry))
    async def stop_animations(event):
        await coordinator.async_stop_effects()
    entry.async_on_unload(hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, stop_animations))
    return True


async def async_reload_entry(hass, entry):
    """Apply saved layout changes through the standard integration lifecycle."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass, entry):
    """Unload entities without changing the physical lights."""
    if await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        coordinator = hass.data[DOMAIN].pop(entry.entry_id)
        await coordinator.async_stop_effects()
        return True
    return False
# AI: end
