"""UI configuration for IP address and named inclusive block ranges."""
# AI: below section was generated by an AI
from copy import deepcopy
import ipaddress
from uuid import uuid4

import voluptuous as vol
from homeassistant import config_entries
from homeassistant.core import callback

from .const import DEFAULT_SLOT, DOMAIN, MODULE
from .model import validate_layout
from .protocol import WizClient, WizError


def integer(low, high):
    return vol.All(vol.Coerce(int), vol.Range(min=low, max=high))


def settings_schema(settings):
    return vol.Schema({
        vol.Required("host", **({"default": settings["host"]} if "host" in settings else {})): str,
        vol.Required("total_blocks", **({"default": settings["total_blocks"]} if "total_blocks" in settings else {})): integer(1, 500),
        vol.Required("slot", default=settings.get("slot", DEFAULT_SLOT)): integer(256, 265),
    })


async def identify(host):
    """Reject incompatible modules without sending any lighting command."""
    try:
        host = str(ipaddress.IPv4Address(host.strip()))
    except ValueError as err:
        raise ValueError("invalid_host") from err
    try:
        system = await WizClient(host).request("getSystemConfig")
    except WizError as err:
        raise ValueError("cannot_connect") from err
    if system.get("moduleName") != MODULE or not system.get("mac"):
        raise ValueError("unsupported_device")
    return host, system


class WizSegmentsFlow(config_entries.ConfigFlow, domain=DOMAIN):
    VERSION = 1

    async def async_step_user(self, user_input=None):
        errors = {}
        if user_input is not None:
            try:
                host, system = await identify(user_input["host"])
            except ValueError as err:
                errors["base"] = str(err)
            else:
                await self.async_set_unique_id(system["mac"].lower())
                self._abort_if_unique_id_configured()
                total = user_input["total_blocks"]
                count = min(3, total)
                segments = [{"id": uuid4().hex, "name": f"Segment {i + 1}",
                             "start": i * total // count + 1, "end": (i + 1) * total // count}
                            for i in range(count)]
                return self.async_create_entry(title="WiZ RGBIC", data={
                    **user_input, "host": host, "segments": segments,
                })
        return self.async_show_form(step_id="user", data_schema=settings_schema(user_input or {}), errors=errors)

    @staticmethod
    @callback
    def async_get_options_flow(config_entry):
        return SegmentOptions(config_entry)


class SegmentOptions(config_entries.OptionsFlow):
    """Stage edits until Save; never change lighting from an options form."""

    def __init__(self, entry):
        self.entry = entry
        self.settings = deepcopy({**entry.data, **entry.options})
        self.edit_id = None

    async def async_step_init(self, user_input=None):
        return self.async_show_menu(step_id="init", menu_options=["add", "edit", "remove", "device", "save"])

    def selection_schema(self):
        return vol.Schema({vol.Required("segment"): vol.In({
            s["id"]: f"{s['name']} ({s['start']}-{s['end']})" for s in self.settings["segments"]
        })})

    async def async_step_add(self, user_input=None):
        self.edit_id = None
        return await self.async_step_segment(user_input)

    async def async_step_edit(self, user_input=None):
        if user_input is not None:
            self.edit_id = user_input["segment"]
            return await self.async_step_segment()
        return self.async_show_form(step_id="edit", data_schema=self.selection_schema())

    async def async_step_segment(self, user_input=None):
        errors = {}
        if user_input is not None:
            segment = {**user_input, "name": user_input["name"].strip(), "id": self.edit_id or uuid4().hex}
            candidate = [s for s in self.settings["segments"] if s["id"] != self.edit_id] + [segment]
            try:
                validate_layout(candidate, self.settings["total_blocks"])
            except ValueError as err:
                errors["base"] = str(err)
            else:
                self.settings["segments"] = candidate
                return await self.async_step_init()
        selected = next((s for s in self.settings["segments"] if s["id"] == self.edit_id), {})
        defaults = user_input or selected
        schema = vol.Schema({
            vol.Required("name", default=defaults.get("name", "Segment")): str,
            vol.Required("start", default=defaults.get("start", 1)): integer(1, self.settings["total_blocks"]),
            vol.Required("end", default=defaults.get("end", 1)): integer(1, self.settings["total_blocks"]),
        })
        return self.async_show_form(step_id="segment", data_schema=schema, errors=errors)

    async def async_step_remove(self, user_input=None):
        errors = {}
        if user_input is not None:
            candidate = [s for s in self.settings["segments"] if s["id"] != user_input["segment"]]
            try:
                validate_layout(candidate, self.settings["total_blocks"])
            except ValueError as err:
                errors["base"] = str(err)
            else:
                self.settings["segments"] = candidate
                return await self.async_step_init()
        return self.async_show_form(step_id="remove", data_schema=self.selection_schema(), errors=errors)

    async def async_step_device(self, user_input=None):
        errors = {}
        if user_input is not None:
            try:
                host, system = await identify(user_input["host"])
                if system["mac"].lower() != self.entry.unique_id:
                    raise ValueError("wrong_device")
                validate_layout(self.settings["segments"], user_input["total_blocks"])
            except ValueError as err:
                errors["base"] = str(err)
            else:
                self.settings.update({**user_input, "host": host})
                return await self.async_step_init()
        return self.async_show_form(step_id="device", data_schema=settings_schema(user_input or self.settings), errors=errors)

    async def async_step_save(self, user_input=None):
        return self.async_create_entry(title="", data=self.settings)
# AI: end
