"""Constants for the experimentally validated WiZ RGBIC protocol."""
# AI: below section was generated by an AI
DOMAIN = "wiz_segments"
MODULE = "ESP25_MHORGB_01"
LEDS_PER_BLOCK = 6
MAX_STEPS = 12
DEFAULT_SLOT = 258
# AI: end
