"""Serialize frame writes and monitor the device without replaying on startup."""
# AI: below section was generated by an AI
import asyncio
from datetime import timedelta
import logging

from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.storage import Store
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed

from .const import DOMAIN
from .model import changed_states, compose_frame, restore_states
from .protocol import WizError

LOGGER = logging.getLogger(__name__)


class SegmentCoordinator(DataUpdateCoordinator):
    """Track last commanded colors; the firmware does not report segment data."""

    def __init__(self, hass, entry, client, system):
        super().__init__(hass, LOGGER, name=DOMAIN, update_interval=timedelta(seconds=10))
        self.client = client
        self.system = system
        self.settings = {**entry.data, **entry.options}
        self.segments = self.settings["segments"]
        self.states = restore_states(self.segments, {})
        self.frame_known = False
        self.lock = asyncio.Lock()
        self.store = Store(hass, 1, f"{DOMAIN}.{entry.entry_id}")

    async def async_load(self):
        """Restore color preferences only; startup never changes the strip."""
        saved = await self.store.async_load()
        self.states = restore_states(self.segments, saved)

    def observe(self, pilot):
        """Invalidate our frame when the strip is off or another mode takes over."""
        if not isinstance(pilot.get("state"), bool):
            raise WizError("Missing power state")
        if not pilot["state"] or pilot.get("sceneId") != self.settings["slot"]:
            self.frame_known = False
        return pilot

    async def _async_update_data(self):
        async with self.lock:
            try:
                return self.observe(await self.client.request("getPilot"))
            except WizError as err:
                self.frame_known = False
                raise UpdateFailed(str(err)) from err

    async def async_set_segment(self, segment_id, on, rgb=None, brightness=None, *, rgbww=None):
        """Apply one edit to a serialized full-strip frame, then persist it."""
        async with self.lock:
            try:
                pilot = self.observe(await self.client.request("getPilot"))
                # Unknown external colors cannot be reconstructed. Start others
                # dark instead of accidentally replaying an old saved scene.
                candidate = changed_states(self.states, segment_id, on, rgb, brightness,
                                           reset_others=not self.frame_known, rgbww=rgbww)
                # An isolated OFF must not turn off an externally controlled strip.
                if not on and pilot["state"] and not self.frame_known:
                    raise HomeAssistantError("Segment colors are unknown after external control. Turn a segment on to resume segment control.")
                payload = compose_frame(self.segments, candidate, self.settings["total_blocks"],
                                        self.settings["slot"], self.system["mac"])
                await self.client.request("setPilot", payload)
                self.states = candidate
                self.frame_known = payload["state"]
                self.async_set_updated_data({"state": payload["state"],
                                             "sceneId": self.settings["slot"], "dimming": 100})
                # Coalesce disk writes while sliders are dragged; HA flushes on shutdown.
                self.store.async_delay_save(lambda: self.states, 1)
            except WizError as err:
                self.frame_known = False
                self.async_set_update_error(UpdateFailed(str(err)))
                raise HomeAssistantError(str(err)) from err
# AI: end
