"""Deterministic animations within the strip's twelve-region wire budget."""
# AI: below section was generated by an AI
import colorsys
from copy import deepcopy
import math

from .const import MAX_STEPS
from .model import compose_frame, has_output, validate_layout

EFFECTS = ["off", "Rainbow", "Chase", "Breathe", "Color loop"]
SPATIAL_EFFECTS = {"Rainbow", "Chase"}


def active_effects(states, effects):
    return {key: effect for key, effect in effects.items()
            if effect != "off" and states[key]["on"]
            and (has_output(states[key]) or effect in {"Rainbow", "Color loop"})}


def render_frame(segments, states, total_blocks, slot, mac, effects, elapsed, period=6):
    """Keep static segments intact and fairly share spare regions among effects."""
    validate_layout(segments, total_blocks)
    active = active_effects(states, effects)
    if not active:
        return compose_frame(segments, states, total_blocks, slot, mac)
    ordered = sorted(segments, key=lambda item: item["start"])
    cursor, used = 1, 0
    slices = {s["id"]: 1 for s in ordered}
    for s in ordered:
        used += 1 + int(s["start"] > cursor)
        cursor = s["end"] + 1
    used += int(cursor <= total_blocks)
    while used < MAX_STEPS:
        changed = False
        for s in ordered:
            key = s["id"]
            if active.get(key) in SPATIAL_EFFECTS and slices[key] < s["end"] - s["start"] + 1:
                slices[key] += 1
                used += 1
                changed = True
                if used == MAX_STEPS:
                    break
        if not changed:
            break
    phase = (elapsed / max(1, period)) % 1
    rendered, pixels = [], {}
    for s in ordered:
        key, length = s["id"], s["end"] - s["start"] + 1
        effect, count = active.get(key, "off"), slices[key]
        for i in range(count):
            pixel_id = f"{key}:{i}"
            rendered.append({"id": pixel_id, "name": s["name"],
                             "start": s["start"] + i * length // count,
                             "end": s["start"] + (i + 1) * length // count - 1})
            state = deepcopy(states[key])
            if effect in {"Rainbow", "Color loop"}:
                hue = (phase + (i / count if effect == "Rainbow" else 0)) % 1
                state["rgb"] = [round(v * 255) for v in colorsys.hsv_to_rgb(hue, 1, 1)]
                state["cold_white"] = state["warm_white"] = 0
            elif effect == "Breathe":
                state["brightness"] = max(1, round(state["brightness"] * (0.1 + 0.9 * (1 - math.cos(phase * 2 * math.pi)) / 2)))
            elif effect == "Chase":
                # A dim background avoids power cycling when a region is dark.
                state["brightness"] = max(1, round(state["brightness"] * (1 if i == int(phase * count) else 0.08)))
            pixels[pixel_id] = state
    return compose_frame(rendered, pixels, total_blocks, slot, mac)
# AI: end
