"""Length-based layout editing while preserving existing entity identities."""
# AI: below section was generated by an AI
from uuid import uuid4

from .model import validate_layout


def distribute_segments(existing, count, total):
    """Redistribute the full strip evenly, retaining IDs in physical order."""
    if type(count) is not int or not 1 <= count <= min(12, total):
        raise ValueError("invalid_layout")
    ordered = sorted(existing, key=lambda s: s["start"])
    result = []
    for i in range(count):
        previous = ordered[i] if i < len(ordered) else {"id": uuid4().hex, "name": f"Segment {i + 1}"}
        result.append({"id": previous["id"], "name": previous["name"],
                       "start": i * total // count + 1, "end": (i + 1) * total // count})
    validate_layout(result, total)
    return result


def resize_segment(existing, key, name, start, blocks, total, auto_arrange):
    """Optionally pack segments after changing a length; never silently truncate."""
    if type(blocks) is not int or blocks < 1:
        raise ValueError("invalid_layout")
    ordered = sorted(existing, key=lambda s: s["start"])
    candidate = []
    found = False
    for s in ordered:
        if s["id"] == key:
            candidate.append({"id": key, "name": name.strip(), "start": start, "end": start + blocks - 1})
            found = True
        else:
            candidate.append(dict(s))
    if not found:
        candidate.append({"id": key, "name": name.strip(), "start": start, "end": start + blocks - 1})
    if auto_arrange:
        cursor = 1
        for s in candidate:
            length = s["end"] - s["start"] + 1
            s["start"], s["end"] = cursor, cursor + length - 1
            cursor += length
    validate_layout(candidate, total)
    return candidate
# AI: end
