"""One Home Assistant RGBWW light per user-defined region."""
# AI: below section was generated by an AI
from homeassistant.components.light import ATTR_BRIGHTNESS, ATTR_RGBWW_COLOR, ColorMode, LightEntity
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN, LEDS_PER_BLOCK
from .model import has_output


async def async_setup_entry(hass, entry, async_add_entities):
    coordinator = hass.data[DOMAIN][entry.entry_id]
    async_add_entities(SegmentLight(coordinator, entry, segment) for segment in coordinator.segments)


class SegmentLight(CoordinatorEntity, LightEntity):
    """Expose the five controls validated visually, without asserting emitter type."""

    _attr_has_entity_name = True
    _attr_supported_color_modes = {ColorMode.RGBWW}
    _attr_color_mode = ColorMode.RGBWW
    _attr_assumed_state = True

    def __init__(self, coordinator, entry, segment):
        super().__init__(coordinator)
        self.segment = segment
        self._attr_name = segment["name"]
        self._attr_unique_id = f"{entry.unique_id}_{segment['id']}"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, entry.unique_id)}, name=entry.title,
            manufacturer="WiZ", model=coordinator.system["moduleName"],
            sw_version=coordinator.system.get("fwVersion"),
        )

    @property
    def is_on(self):
        if not self.coordinator.data.get("state"):
            return False
        if not self.coordinator.frame_known:
            return None
        state = self.coordinator.states[self.segment["id"]]
        return state["on"] and has_output(state)

    @property
    def brightness(self):
        return self.coordinator.states[self.segment["id"]]["brightness"]

    @property
    def rgbww_color(self):
        state = self.coordinator.states[self.segment["id"]]
        return (*state["rgb"], state["cold_white"], state["warm_white"])

    @property
    def extra_state_attributes(self):
        return {"start_block": self.segment["start"], "end_block": self.segment["end"],
                "first_led": (self.segment["start"] - 1) * LEDS_PER_BLOCK + 1,
                "last_led": self.segment["end"] * LEDS_PER_BLOCK,
                "segment_state_known": self.coordinator.frame_known}

    async def async_turn_on(self, **kwargs):
        await self.coordinator.async_set_segment(self.segment["id"], True,
                                                brightness=kwargs.get(ATTR_BRIGHTNESS),
                                                rgbww=kwargs.get(ATTR_RGBWW_COLOR))

    async def async_turn_off(self, **kwargs):
        await self.coordinator.async_set_segment(self.segment["id"], False)
# AI: end
