"""Pure segment layout and full-frame composition; no Home Assistant imports."""
# AI: below section was generated by an AI
from copy import deepcopy

from .const import MAX_STEPS


def validate_layout(segments, total_blocks):
    """Validate inclusive block ranges and reserve wire steps for dark gaps."""
    if type(total_blocks) is not int or not 1 <= total_blocks <= 500:
        raise ValueError("invalid_layout")
    if not 1 <= len(segments) <= MAX_STEPS:
        raise ValueError("invalid_layout")
    ids = set()
    cursor = 1
    count = 0
    for segment in sorted(segments, key=lambda item: item["start"]):
        start, end = segment["start"], segment["end"]
        if (type(start) is not int or type(end) is not int
                or not cursor <= start <= end <= total_blocks
                or not str(segment["name"]).strip()
                or not isinstance(segment["id"], str) or not segment["id"]
                or segment["id"] in ids):
            raise ValueError("invalid_layout")
        ids.add(segment["id"])
        count += 1 + int(start > cursor)
        cursor = end + 1
    # Explicitly cover the tail with black so a shorter new layout clears it.
    count += int(cursor <= total_blocks)
    if count > MAX_STEPS:
        raise ValueError("too_many_steps")


def default_state():
    """Start dark with a modest remembered brightness for the first command."""
    return {"on": False, "rgb": [255, 255, 255], "cold_white": 0, "warm_white": 0, "brightness": 64}


def has_output(state):
    """Pure white must remain lit even when every RGB channel is zero."""
    return any(state["rgb"]) or state.get("cold_white", 0) > 0 or state.get("warm_white", 0) > 0


def restore_states(segments, saved):
    """Read saved preferences defensively, never issuing a hardware command."""
    restored = {}
    for segment in segments:
        state = default_state()
        candidate = saved.get(segment["id"], {}) if isinstance(saved, dict) else {}
        if isinstance(candidate, dict):
            rgb = candidate.get("rgb")
            if isinstance(rgb, (list, tuple)) and len(rgb) == 3 and all(type(v) is int and 0 <= v <= 255 for v in rgb):
                state["rgb"] = list(rgb)
            for channel in ("cold_white", "warm_white"):
                value = candidate.get(channel, 0)
                if type(value) is int and 0 <= value <= 255:
                    state[channel] = value
            brightness = candidate.get("brightness")
            if type(brightness) is int and 1 <= brightness <= 255:
                state["brightness"] = brightness
            state["on"] = candidate.get("on") is True
        restored[segment["id"]] = state
    return restored


def changed_states(states, segment_id, on, rgb=None, brightness=None, reset_others=False, *, rgbww=None):
    """Compose a candidate copy; the caller commits only after acknowledgment."""
    result = deepcopy(states)
    if reset_others:
        for state in result.values():
            state["on"] = False
    state = result[segment_id]
    state["on"] = on
    if rgbww is not None:
        if rgb is not None or len(rgbww) != 5 or any(type(v) is not int or not 0 <= v <= 255 for v in rgbww):
            raise ValueError("Invalid RGBWW value")
        # HA order is R,G,B,cold,warm; wire order is R,G,B,warm,cold.
        state["rgb"] = list(rgbww[:3])
        state["cold_white"], state["warm_white"] = rgbww[3:]
    if rgb is not None:
        if len(rgb) != 3 or any(type(v) is not int or not 0 <= v <= 255 for v in rgb):
            raise ValueError("Invalid RGB value")
        state["rgb"] = list(rgb)
        state["cold_white"] = state["warm_white"] = 0
    if brightness is not None:
        if type(brightness) is not int or not 0 <= brightness <= 255:
            raise ValueError("Invalid brightness")
        if brightness == 0:
            state["on"] = False
        else:
            state["brightness"] = brightness
    return result


def compose_frame(segments, states, total_blocks, slot, mac):
    """Render the complete strip so a change cannot overwrite other segments."""
    validate_layout(segments, total_blocks)
    if type(slot) is not int or not 256 <= slot <= 265:
        raise ValueError("Invalid custom slot")
    if not any(state["on"] and has_output(state) for state in states.values()):
        return {"state": False}
    steps = []
    cursor = 1

    def append_step(width, rgb, dimming, warm=0, cold=0):
        # Indices 4=warm and 5=cold were visually verified on this device.
        steps.append([0, *rgb, warm, cold, 0, dimming, 0, 0, 0, 0, width])

    for segment in sorted(segments, key=lambda item: item["start"]):
        if segment["start"] > cursor:
            append_step(segment["start"] - cursor, (0, 0, 0), 0)
        state = states[segment["id"]]
        lit = state["on"] and has_output(state)
        rgb = state["rgb"] if lit else (0, 0, 0)
        dimming = max(1, round(state["brightness"] * 100 / 255)) if lit else 0
        append_step(segment["end"] - segment["start"] + 1, rgb, dimming,
                    state.get("warm_white", 0) if lit else 0,
                    state.get("cold_white", 0) if lit else 0)
        cursor = segment["end"] + 1
    if cursor <= total_blocks:
        append_step(total_blocks - cursor + 1, (0, 0, 0), 0)
    return {"mac": mac, "state": True, "sceneId": slot, "dimming": 100,
            "elm": {"modifier": 100, "support": 17, "steps": steps}}
# AI: end
