"""Independent implementation of the WiZ local RGBIC wire protocol.

Protocol findings: https://github.com/TechAntohere/WizScreenSyncController/
Hardware validation: see HARDWARE.md in this project.
"""
# AI: below section was generated by an AI
import asyncio
import ipaddress
import json
import socket


class WizError(Exception):
    """A command was rejected, malformed, or not acknowledged."""


class WizClient:
    """Use a fresh connected socket per RPC to exclude stale replies."""

    def __init__(self, host, port=38899, timeout=3):
        self.host = str(ipaddress.IPv4Address(host))
        self.port = port
        self.timeout = timeout

    async def request(self, method, params=None):
        """Bound each attempt and only accept replies from this device/method."""
        loop = asyncio.get_running_loop()
        payload = json.dumps({"method": method, "params": params or {}}, separators=(",", ":")).encode()
        for attempt in range(2):
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
                sock.setblocking(False)
                try:
                    async with asyncio.timeout(self.timeout):
                        await loop.sock_connect(sock, (self.host, self.port))
                        await loop.sock_sendall(sock, payload)
                        while True:
                            raw = await loop.sock_recv(sock, 8192)
                            try:
                                reply = json.loads(raw)
                            except (ValueError, UnicodeError):
                                continue
                            if not isinstance(reply, dict) or reply.get("method") != method:
                                continue
                            if "error" in reply:
                                raise WizError(f"{method}: {reply['error']}")
                            result = reply.get("result")
                            if not isinstance(result, dict):
                                raise WizError(f"{method}: invalid reply")
                            if method == "setPilot" and result.get("success") is not True:
                                raise WizError("Command not acknowledged")
                            return result
                except (TimeoutError, OSError) as err:
                    if attempt:
                        raise WizError(f"No reply from {self.host}") from err
        raise WizError("No reply")
# AI: end
