"""Inspect a WiZ strip; optionally run a short, restored segment test.

Protocol reference: https://github.com/TechAntohere/WizScreenSyncController/
This is a hardware validation tool, not a Home Assistant integration.
"""
# AI: below section was generated by an AI
import argparse
import json
import socket
import time


def request(host, method, params):
    """Query only the requested peer, with a bounded receive deadline."""
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.settimeout(3)
        sock.connect((host, 38899))
        sock.send(json.dumps({"method": method, "params": params}).encode())
        deadline = time.monotonic() + 3
        while time.monotonic() < deadline:
            sock.settimeout(max(0.01, deadline - time.monotonic()))
            packet = json.loads(sock.recv(8192))
            if packet.get("method") != method:
                continue
            if "error" in packet:
                raise RuntimeError(str(packet["error"]))
            result = packet.get("result")
            if not isinstance(result, dict):
                raise RuntimeError("Malformed WiZ reply")
            return result
        raise TimeoutError("No matching WiZ reply")


def color_steps(width):
    """Build three contiguous RGB regions in physical block units, not LEDs."""
    if not 1 <= width <= 100:
        raise ValueError("Width must be between 1 and 100")
    steps = []
    for rgb in ((255, 0, 0), (0, 255, 0), (0, 0, 255)):
        steps.append([0, *rgb, 0, 0, 0, 10, 0, 0, 0, 0, width])
    return steps


def test_segments(host, system, original, slot, width, seconds):
    """Test one explicitly selected slot; restore OFF even if a request fails.

    Testing is restricted to a strip that is initially off, because getPilot
    cannot provide enough data to restore a previously displayed segment frame.
    A successful reply still requires visual confirmation from the user.
    """
    if system.get("moduleName") != "ESP25_MHORGB_01":
        raise ValueError("This test is restricted to ESP25_MHORGB_01")
    if original.get("state") is not False:
        raise ValueError("Switch the strip off before testing; no changes sent")
    if not 256 <= slot <= 265 or not 1 <= seconds <= 60:
        raise ValueError("Invalid slot or test duration")
    params = {
        "mac": system["mac"], "state": True, "sceneId": slot,
        "dimming": 10,
        "elm": {"modifier": 100, "support": 17, "steps": color_steps(width)},
    }
    # Retain ordinary color/scene parameters as well as restoring the off state.
    fields = ("sceneId", "r", "g", "b", "c", "w", "temp", "dimming", "speed")
    restore = {key: original[key] for key in fields if key in original}
    if restore.get("sceneId", 0):
        restore = {key: value for key, value in restore.items()
                   if key in ("sceneId", "dimming", "speed")}
    else:
        restore.pop("sceneId", None)
        restore.pop("speed", None)
        if restore.get("temp", 0) > 0:
            for key in ("r", "g", "b", "c", "w"):
                restore.pop(key, None)
    restore["state"] = False
    try:
        print("Test reply:", request(host, "setPilot", params), flush=True)
        print("Observe separate RED, GREEN and BLUE blocks; ACK is not proof.", flush=True)
        time.sleep(seconds)
    finally:
        restored = False
        for attempt in range(3):
            try:
                request(host, "setPilot", restore)
                if request(host, "getPilot", {}).get("state") is False:
                    restored = True
                    print("Verified: strip is OFF again.", flush=True)
                    break
            except (OSError, ValueError, RuntimeError):
                # OFF alone remains valid even if saved color fields are rejected.
                try:
                    request(host, "setPilot", {"state": False})
                except (OSError, ValueError, RuntimeError):
                    pass
                time.sleep(0.5)
        if not restored:
            raise RuntimeError("Could not verify restoration: switch the strip off in WiZ")


def main():
    """Default to read-only identification; testing requires an explicit flag."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("host")
    parser.add_argument("--test", action="store_true")
    parser.add_argument("--slot", type=int, default=258)
    parser.add_argument("--width", type=int, default=3)
    parser.add_argument("--seconds", type=int, default=20)
    args = parser.parse_args()
    system = request(args.host, "getSystemConfig", {})
    pilot = request(args.host, "getPilot", {})
    safe_system = {key: system.get(key) for key in ("moduleName", "fwVersion", "mac")}
    safe_pilot = {key: pilot[key] for key in
                  ("state", "sceneId", "dimming", "r", "g", "b", "c", "w", "temp", "speed")
                  if key in pilot}
    print(json.dumps({"system": safe_system, "pilot": safe_pilot}, indent=2))
    if args.test:
        test_segments(args.host, system, pilot, args.slot, args.width, args.seconds)


if __name__ == "__main__":
    main()
# AI: end
