"""Offline checks for the public integration package (no device access)."""
# AI: below section was generated by an AI
import ast
import json
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
TOP_FILES = {"README.md", "README.pt-BR.md", "HARDWARE.md", "LICENSE",
             "CONTRIBUTING.md", "CHANGELOG.md", "hacs.json", ".gitignore", ".gitattributes"}
PUBLIC_DIRS = {"custom_components", "tests", "tools", "docs", ".github"}


def public_files():
    return sorted(p for p in ROOT.rglob("*") if p.is_file()
                  and "__pycache__" not in p.parts and p.suffix != ".pyc"
                  and (p.relative_to(ROOT).parts[0] in PUBLIC_DIRS
                       or p.relative_to(ROOT).as_posix() in TOP_FILES))


def keys(value, prefix=""):
    if not isinstance(value, dict):
        return {prefix}
    return {key for name, child in value.items() for key in keys(child, f"{prefix}/{name}")}


def main():
    component = ROOT / "custom_components/wiz_segments"
    manifest = json.loads((component / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["domain"] == "wiz_segments"
    assert manifest["codeowners"] == ["@thiagolcordeiro"]
    assert re.fullmatch(r"\d+\.\d+\.\d+", manifest["version"])
    assert manifest["documentation"] == "https://github.com/thiagolcordeiro/home-assistant-wiz-segments"
    assert manifest["issue_tracker"] == manifest["documentation"] + "/issues"
    assert "MIT License" in (ROOT / "LICENSE").read_text(encoding="utf-8")
    hacs = json.loads((ROOT / "hacs.json").read_text(encoding="utf-8"))
    assert hacs["content_in_root"] is False
    canonical = keys(json.loads((component / "strings.json").read_text(encoding="utf-8")))
    for path in (component / "translations").glob("*.json"):
        assert keys(json.loads(path.read_text(encoding="utf-8"))) == canonical, path
    for path in public_files():
        if path.suffix == ".png":
            payload = path.read_bytes()
            assert payload[:8] == b"\x89PNG\r\n\x1a\n"
            assert struct.unpack(">II", payload[16:24]) == (256, 256)
            continue
        text = path.read_text(encoding="utf-8")
        if path.suffix == ".py":
            ast.parse(text, filename=str(path))
        if path.suffix == ".json":
            json.loads(text)
        if path.suffix == ".md":
            for link in re.findall(r"\]\(([^)]+)\)", text):
                if "://" not in link and not link.startswith("#"):
                    assert (path.parent / link.split("#")[0]).exists(), (path, link)
    assert (component / "brand/icon.png").exists()
    print(f"Public package valid: {len(public_files())} files, version {manifest['version']}")


if __name__ == "__main__":
    main()
# AI: end
